import { ArrowRight, Check, Cookie, Sparkles, UserRound } from 'lucide-react';
import { useState } from 'react';
import { useLocation } from 'wouter';

const GUEST_KEY = 'codezero-guest';
export const getGuestName = () => typeof window === 'undefined' ? '' : localStorage.getItem(GUEST_KEY) || '';
export const leaveGuest = () => { localStorage.removeItem(GUEST_KEY); };

export default function GuestPage() {
  const [, navigate] = useLocation();
  const [name, setName] = useState('');
  const chooseGuest = (profileName: string) => { localStorage.setItem(GUEST_KEY, profileName); localStorage.setItem('codezero-profile-name', profileName); navigate('/app/dashboard'); };
  const startAccount = () => { const profileName = name.trim(); if (!profileName) return; localStorage.setItem('codezero-profile-name', profileName); localStorage.removeItem(GUEST_KEY); navigate('/auth/signup'); };

  return <div className="min-h-screen bg-[#0d0f13] text-[#f1f2f4]"><header className="border-b border-white/[.1]"><div className="container flex h-[72px] items-center justify-between"><a href="/" className="flex items-center gap-3"><span className="flex h-8 w-8 items-center justify-center rounded-md bg-[#b9ee83] font-mono text-[14px] font-bold text-[#14180e]">&gt;_</span><span className="font-display text-[20px] font-semibold tracking-[-.04em]">codezero</span></a><span className="text-[10px] font-bold uppercase tracking-[.16em] text-[#707a86]">modo convidado</span></div></header><main className="container flex min-h-[calc(100vh-72px)] items-center justify-center py-16"><section className="w-full max-w-[680px]"><div className="text-center"><p className="flex items-center justify-center gap-2 text-[10px] font-bold uppercase tracking-[.18em] text-[#b9ee83]"><Sparkles size={13} /> escolha seu perfil</p><h1 className="mt-5 font-display text-5xl leading-[.94] tracking-[-.07em] text-white sm:text-6xl">Quem está<br/><span className="text-[#b9ee83]">codando hoje?</span></h1><p className="mx-auto mt-5 max-w-[430px] text-[14px] leading-[1.7] text-[#9da6b2]">Escolha um convidado para entrar. Seu progresso fica salvo neste navegador para você voltar quando quiser.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2"><GuestCard name="Cookie" detail="perfil principal" accent="#b9ee83" icon={<Cookie size={28} />} onClick={() => chooseGuest('Cookie')} /><GuestCard name="Pê" detail="perfil convidado" accent="#a996ff" icon={<UserRound size={28} />} onClick={() => chooseGuest('Pê')} /></div><div className="mt-5 glass rounded-[18px] p-5"><div className="flex items-center gap-2 text-[#b9ee83]"><Check size={15} /><span className="text-[11px] font-bold">Quer uma conta normal?</span></div><p className="mt-2 text-[11px] leading-relaxed text-[#8792a3]">Escolha seu nome primeiro. Depois você entra pelo acesso seguro e mantém seu perfil.</p><div className="mt-4 flex flex-col gap-2 sm:flex-row"><input value={name} onChange={(e) => setName(e.target.value)} maxLength={24} placeholder="Como quer ser chamado?" className="h-10 min-w-0 flex-1 rounded-xl border border-white/[.1] bg-white/[.03] px-3 text-[11px] text-white outline-none placeholder:text-[#596477] focus:border-[#b9ee83]/40" /><button disabled={!name.trim()} onClick={startAccount} className="rounded-xl bg-[#b9ee83] px-4 py-2.5 text-[10px] font-extrabold text-[#14180e] disabled:opacity-40">Criar conta normal <ArrowRight size={13} className="ml-1 inline" /></button></div></div><p className="mt-6 text-center text-[10px] leading-relaxed text-[#6f7986]">O modo convidado não exige cadastro. A conta normal usa o acesso seguro do CodeZero.</p></section></main></div>;
}

function GuestCard({ name, detail, accent, icon, onClick }: { name: string; detail: string; accent: string; icon: React.ReactNode; onClick: () => void }) { return <button onClick={onClick} className="group glass neon-card relative overflow-hidden rounded-[16px] p-6 text-left transition-transform active:scale-[.98]" style={{ '--guest-accent': accent } as React.CSSProperties}><div className="absolute inset-x-0 top-0 h-[2px] opacity-60" style={{ background: accent }} /><div className="flex items-start justify-between"><span className="flex h-14 w-14 items-center justify-center rounded-xl" style={{ color: accent, background: `${accent}15` }}>{icon}</span><ArrowRight size={17} className="text-[#66717e] transition-transform group-hover:translate-x-1" /></div><h2 className="mt-8 font-display text-3xl tracking-[-.05em] text-white">{name}</h2><p className="mt-1 text-[11px] uppercase tracking-[.14em] text-[#7d8793]">{detail}</p><div className="mt-8 flex items-center gap-2 text-[11px] font-bold" style={{ color: accent }}>Entrar como {name} <ArrowRight size={13} /></div></button>; }
